"""empty message

Revision ID: 11b3a72d2ea
Revises: 42f362c60c6
Create Date: 2014-10-22 11:00:57.459375

"""

# revision identifiers, used by Alembic.
revision = '11b3a72d2ea'
down_revision = '42f362c60c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
