"""empty message

Revision ID: 42f362c60c6
Revises: 4f1cdde08da
Create Date: 2014-10-22 11:00:42.800532

"""

# revision identifiers, used by Alembic.
revision = '42f362c60c6'
down_revision = '4f1cdde08da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
