"""empty message

Revision ID: df04d5899e5
Revises: 5430d4506a69
Create Date: 2014-10-17 15:25:02.384885

"""

# revision identifiers, used by Alembic.
revision = 'df04d5899e5'
down_revision = '5430d4506a69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
